import car1 from "./assets/testdrive1.png";
import car2 from "./assets/testdrive2.png";
import car3 from "./assets/testdrive3.png";
import car4 from "./assets/testdrive4.png";

import tdCar1 from "./assets/testdrive1.png";
import tdCar2 from "./assets/testdrive2.png";
import tdCar3 from "./assets/testdrive3.png";
import tdCar4 from "./assets/testdrive4.png";
import tdCar5 from "./assets/testdrive5.png";
import tdCar6 from "./assets/testdrive6.png";

const Cars = [
  {
    id: 1,
    model: "TESLA MODEL 3 2018",
    price: "38000",
    testdriveImg: tdCar1,
    frontImgs: [car1, car2, car3],
    specs: [{a:"1",b:"1"},{a:"2",b:"2"},{a:"3",b:"3"},{a:"4",b:"4"},{a:"5",b:"5"},{a:"6",b:"6"},{a:"7",b:"7"},{a:"8",b:"8"}],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    characteristics:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    complect:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
  },
  {
    id: 2,
    model: "TESLA MODEL 3 2017",
    price: "35000",
    testdriveImg: tdCar2,
    frontImgs: [car2, car3, car4],
    specs: [{a:"1",b:"1"},{a:"2",b:"2"},{a:"3",b:"3"},{a:"4",b:"4"},{a:"5",b:"5"},{a:"6",b:"6"},{a:"7",b:"7"},{a:"8",b:"8"}],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    characteristics:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    complect:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
  },
  {
    id: 3,
    model: "TESLA MODEL 3 2016",
    price: "33000",
    testdriveImg: tdCar3,
    frontImgs: [car3, car4, car1],
    specs: [{a:"1",b:"1"},{a:"2",b:"2"},{a:"3",b:"3"},{a:"4",b:"4"},{a:"5",b:"5"},{a:"6",b:"6"},{a:"7",b:"7"},{a:"8",b:"8"}],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    characteristics:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    complect:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
  },
  {
    id: 4,
    model: "TESLA MODEL 3 2015",  //++
    price: "38000",               //++
    testdriveImg: tdCar4,
    frontImgs: [car4, car1, car2],
    specs: [{a:"1",b:"1"},{a:"2",b:"2"},{a:"3",b:"3"},{a:"4",b:"4"},{a:"5",b:"5"},{a:"6",b:"6"},{a:"7",b:"7"},{a:"8",b:"8"}],
    description:  //++
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    characteristics:  //++
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    complect:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
  },
  {
    id: 5,
    model: "TESLA MODEL 3 2014",
    price: "35000",
    testdriveImg: tdCar5,
    frontImgs: [car1, car2, car3],
    specs: [{a:"1",b:"1"},{a:"2",b:"2"},{a:"3",b:"3"},{a:"4",b:"4"},{a:"5",b:"5"},{a:"6",b:"6"},{a:"7",b:"7"},{a:"8",b:"8"}],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    characteristics:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    complect:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
  },
  {
    id: 6,
    model: "TESLA MODEL 3 2013",
    price: "33000",
    testdriveImg: tdCar6,
    frontImgs: [car2, car3, car4],
    specs: [{a:"1",b:"1"},{a:"2",b:"2"},{a:"3",b:"3"},{a:"4",b:"4"},{a:"5",b:"5"},{a:"6",b:"6"},{a:"7",b:"7"},{a:"8",b:"8"}],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    characteristics:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
    complect:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut aliquam purus sit amet luctus. Ullamcorper sit amet risus nullam eget felis. Praesent tristique magna sit amet purus gravida quis blandit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Vivamus at augue eget arcu dictum varius duis at consectetur. Vulputate ut pharetra sit amet aliquam id diam maecenas. Dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit pellentesque. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing at in tellus integer feugiat scelerisque. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices dui sapien eget mi proin. Tempus urna et pharetra pharetra massa massa. Vestibulum sed arcu non odio euismod. Elit pellentesque habitant morbi tristique.Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Viverra mauris in aliquam sem fringilla ut morbi. Molestie a iaculis at erat pellentesque. Posuere urna nec tincidunt praesent semper feugiat. Turpis nunc eget lorem dolor. Aliquam eleifend mi in nulla posuere sollicitudin. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Tortor consequat id porta nibh venenatis cras sed felis eget. Egestas fringilla phasellus faucibus scelerisque. Vitae purus faucibus ornare suspendisse sed nisi. Purus ut faucibus pulvinar",
  },
];

export default Cars;